root = "."
tmp_dir = "var/air_tmp"

[build]
  args_bin = []
  bin = "./var/air_temp/sensemon"
  cmd = "make air"
  delay = 0
  exclude_dir = ["var"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = "DISABLE_CSP=1 ./var/air_temp/sensemon"
  include_dir = []
  include_ext = ["go","yaml","trigger","html"]
  include_file = []
  kill_delay = 150 # ms
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = true
  rerun_delay = 2000
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

